### ISSUE TITLE
`Cannot read field "desc" because "frame[varInsn.var]" is null`

### ISSUE THREAD

**Issue by SettingDust** [TelepathicGrunt/StructureVoidToggle#6]
1.20.1 Quilt 0.20.2. 4.2.6
```
[17:08:32] [Render thread/ERROR] (Quilt Loader/Mixin) Mixin apply for mod structure_void_toggle failed #structure_void_toggle:structure_void_toggle.mixins.json:client.KeyboardHandlerMixin from mod structure_void_toggle -> net.minecraft.class_309: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> #structure_void_toggle:structure_void_toggle.mixins.json:client.KeyboardHandlerMixin from mod structure_void_toggle -> Apply Injections -> PreInject -> #structure_void_toggle:structure_void_toggle.mixins.json:client.KeyboardHandlerMixin from mod structure_void_toggle->@Inject::keyPress(JIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> #structure_void_toggle:structure_void_toggle.mixins.json:client.KeyboardHandlerMixin from mod structure_void_toggle -> Apply Injections -> PreInject -> #structure_void_toggle:structure_void_toggle.mixins.json:client.KeyboardHandlerMixin from mod structure_void_toggle->@Inject::keyPress(JIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1393) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:457) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.20.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:502) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.20.2.jar:?]
Caused by: java.lang.NullPointerException: Cannot read field "desc" because "frame[varInsn.var]" is null
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:546) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:336) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.preInject(CallbackInjector.java:479) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:258) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1370) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	... 23 more
[17:08:32] [Render thread/WARN] (Quilt Loader/Knot) Mixin transformation of net.minecraft.class_309 failed
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:457) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.20.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:502) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.20.2.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#structure_void_toggle:structure_void_toggle.mixins.json:client.KeyboardHandlerMixin from mod structure_void_toggle] from phase [DEFAULT] in config [#structure_void_toggle:structure_void_toggle.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> #structure_void_toggle:structure_void_toggle.mixins.json:client.KeyboardHandlerMixin from mod structure_void_toggle -> Apply Injections -> PreInject -> #structure_void_toggle:structure_void_toggle.mixins.json:client.KeyboardHandlerMixin from mod structure_void_toggle->@Inject::keyPress(JIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1393) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	... 17 more
Caused by: java.lang.NullPointerException: Cannot read field "desc" because "frame[varInsn.var]" is null
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:546) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:336) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.preInject(CallbackInjector.java:479) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:258) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1370) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	... 17 more
```
The mods that mixin into the same class
```
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing ui.layers.KeyboardMixin from #owo:owo.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing MixinKeyboard from #amecs:amecs.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/WARN] (Quilt Loader/Mixin) #amecs:amecs.mixins.json:MixinKeyboard from mod amecs: Class version 60 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing compat.SplashUseFix from #rrls:rrls-common.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing MixinKeyboard from #amecsapi:amecsapi.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing KeyboardMixin from #fabrishot:mixins.fabrishot.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing Mixin_PassEvents_HandleKeys from #replaymod:mixins.jgui.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing MixinKeyboardListener from #replaymod:mixins.jgui.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing KeyboardHandlerMixin from #itemswapper:itemswapper.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing basic.mc263865.KeyboardHandlerMixin from #debugify:debugify.client.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing KeyboardHandlerMixin from #jei:jei.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing KeyboardMixin from #emi:emi.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing KeyboardMixin from #voicechat:voicechat.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing client.MixinKeyboardHandler from #architectury:architectury.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing KeyboardMixin from #betterf3:betterf3.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing KeyboardMixin from #languagereload:languagereload.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing client.KeyboardHandlerMixin from #structure_void_toggle:structure_void_toggle.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing client.KeyboardMixin from #quilt_screen:quilt_screen.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing client.MixinKeyboardHandler from #konkrete:konkrete.mixin.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Renaming synthetic method lambda$onCharTyped$2(II)V to md89706c$konkrete$lambda$onCharTyped$2$0 in #konkrete:konkrete.mixin.json:client.MixinKeyboardHandler from mod konkrete
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Renaming synthetic method lambda$onKeyPressHandleRelease$1(IIII)V to md89706c$konkrete$lambda$onKeyPressHandleRelease$1$1 in #konkrete:konkrete.mixin.json:client.MixinKeyboardHandler from mod konkrete
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Renaming synthetic method lambda$onKeyPressHandlePress$0(IIII)V to md89706c$konkrete$lambda$onKeyPressHandlePress$0$2 in #konkrete:konkrete.mixin.json:client.MixinKeyboardHandler from mod konkrete
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing core.KeyboardHandlerMixin from #controlify:controlify.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing feature.virtualmouse.KeyboardHandlerAccessor from #controlify:controlify.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing client.KeyboardHandlerFabricMixin from #puzzleslib:puzzleslib.fabric.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing KeyboardHandlerMixin from #balm-fabric:balm.mixins.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing MixinKeyboardListener from mixins.core.replaymod.json into net.minecraft.class_309
[17:52:00] [Render thread/INFO] (Quilt Loader/Mixin) Mixing MixinKeyboardListener from mixins.replay.replaymod.json into net.minecraft.class_309
```

**Comment by TelepathicGrunt** [comment]
Ignore me, I see versions at top

**Comment by SettingDust** [comment]
> Ignore me, I see versions at top

Noop. That's my fault. I EDIT the body just now. I'm confusing. I have two instance that one is with lesser mod that is another's subset but crashed. The full instance with more mod not crash. Can't figure out the reason of that

**Comment by TelepathicGrunt** [comment]
Does the larger instance have all the mods of the smaller instance? if not, what mods are present in the smaller instance that the larger doesn't have

**Comment by SettingDust** [comment]
> Does the larger instance have all the mods of the smaller instance? if not, what mods are present in the smaller instance that the larger doesn't have

The larger one has all mods from smaller one. Actually, the small one is synced with FreeFileSync with some filter

**Comment by SettingDust** [comment]
I've tried reproduce with all the mods that mixin into the class_309. But not crashed.
I think I need some hint to find the one that conflict(or not?) with this mod

**Comment by TelepathicGrunt** [comment]
Given that I can run my mod on Quilt without issue myself with my mod alone, my guess is you have a mod in your modpack that is messing with the keyboard class's method in a way that crashes my mixin. Might be mod load order dependent 
  
![image](https://github.com/TelepathicGrunt/StructureVoidToggle/assets/40846040/f6227d45-1678-4997-9162-438753f8d3fc)

![image](https://github.com/TelepathicGrunt/StructureVoidToggle/assets/40846040/a705e547-b79c-4da2-ab63-90d325df6654)

**Comment by TelepathicGrunt** [comment]
Try this jar (unzip first)
[structure_void_toggle-4.2.7-test+1.20.1.zip](https://github.com/TelepathicGrunt/StructureVoidToggle/files/12512537/structure_void_toggle-4.2.7-test%2B1.20.1.zip)

**Comment by SettingDust** [comment]
Works! What's the reason?

**Comment by TelepathicGrunt** [comment]
All I did was remove this line cause I don't use any locals in the mixin. makes me wonder if this is a bug within mixin tool itself https://github.com/TelepathicGrunt/StructureVoidToggle/blob/9f83581eb478706259272387306025ecf395b5fb/src/main/java/com/telepathicgrunt/structurevoidtoggle/mixin/client/KeyboardHandlerMixin.java#L16

**Comment by TelepathicGrunt** [comment]
new jar is now released
